class CreateAnAccountPageLocators():

    # user pesonal information
    genderMr_radiobtn_id = "id_gender1"
    genderMrs_radiobtn_id = "id_gender2"
    userFirstName_textbox_id = "customer_firstname"
    userSecondName_textbox_id = "customer_lastname"
    userEmail_textbox_id = "email"
    userPasswd_textbox_id = "passwd"
    dayOfBirth_dropdownmenu_id = "days"
    dayOfBirth_menuitem_visibletext = "regexp:12\\s+"
    monthOfBirth_dropdownmenu_id = "months"
    monthOfBirth_menuitem_visibletext = "regexp:May\\s"
    yearOfBirth_dropdownmenu_id = "years"
    yearOfBirth_menuitem_visibletext = "regexp:2015\\s+"
    receiveNewsletter_checkbox_id = "newsletter"
    receiveSpecialoffers_checkbox_id = "optin"
    # user address
    firstNameDelivery_textbox_id = "firstname"
    lastNameDelivery_textbox_id = "lastname"
    companyName_textbox_id = "company"
    address_textbox_id = "address1"
    addressLine2_textbox_id = "address2"
    city_textbox_id = "city"
    state_dropdownmenu_id = "id_state"
    state_menuitem_visibletext = "Idaho"
    postCode_textbox_id = "postcode"
    contry_dropdownmenu_id = "id_country"
    additionalInformation_textbox_id = "other"
    mobilePhone_textbox_id = "phone_mobile"
    aliasForAddress_textbox_id = "alias"
    submitAccount_btn_id = "submitAccount"