class HomePageLocators():

    signIn_link_textlink = "Sign in"
    contactUs_link_textlink = "Contact us"
    search_textbox_id = "search_query_top"
    submitSerch_Btn_name = "submit_search"
    cart_link_cssselectors = ".shopping_cart a"
    womanCatg_link_textlink = "Women"
    dressesCatg_link_xpath = "//div[@id='block_top_menu']/ul/li[2]/a"
    tshirtsCatg_link_xpath = "//div[@id='block_top_menu']/ul/li[3]/a"
    prevBtnHomeSlider_btn_class = "bx-prev"
    nextBtnHomeSlider_btn_class = "bx-next"
    popular_link_class = "homefeatured"
    bestsellers_link_class = "blockbestsellers"
    prodItem1_link_xpath = "//img[@alt='Faded Short Sleeve T-shirts']"
    prodItem2_link_xpath = "//img[@alt='Printed Dress']"
    prodItemQuickView_link_class = "quick-view-mobile"
    prodItemCloseQuickView_class = "fancybox-close"
    addToCartQuickView_btn_class = "exclusive"
    prodDeteilView_link_textlink = "More"
    addToCart_btn_xpath = "//ul[@id='homefeatured']/li[2]/div/div[2]/div[2]/a/span"
    closeAddToCartPopUp_btn_cssselector = "span.cross"